---
title: "Final Proposal"
author: "Jack Wright"
date: "10/22/2021"
output:
  tufte::tufte_handout: default
  tufte::tufte_html: default
---



```{r}
library(here)
library(tidyverse)
df_raw <- read.csv(here('kaggle_files',"test.csv"), header = T, stringsAsFactors = F, colClasses = c(fullVisitorId = "character"))
df_small=head(df_raw)
```


```{r}
df_device <- paste("[", paste(df_small$device, collapse = ","), "]") %>% fromJSON(flatten = T)
df_geoNetwork <- paste("[", paste(df$geoNetwork, collapse = ","), "]") %>% fromJSON(flatten = T)
df_totals <- paste("[", paste(df_small$totals, collapse = ","), "]") %>% fromJSON(flatten = T)
df_trafficSource <- paste("[", paste(df$trafficSource, collapse = ","), "]") %>% fromJSON(flatten = T)


df <- df %>%
    cbind(df_device, df_geoNetwork, df_totals, df_trafficSource) %>%
    select(-device, -geoNetwork, -totals, -trafficSource)

factorVars <- c("channelGrouping", "browser", "operatingSystem", "deviceCategory", "country")
df[, factorVars] <- lapply(df[, factorVars], as.factor)
df$transactionRevenue <- as.numeric(df$transactionRevenue)

numVars <- c("visits", "hits", "bounces", "pageviews", "newVisits")
df[, numVars] <- lapply(df[, numVars], as.integer)

df$visitStartTime <- as.POSIXct(df$visitStartTime, tz="UTC", origin='1970-01-01')
write.csv(df, here('kaggle_files','test_clean.csv'), row.names = FALSE)

```


